# Generated by Django 6.0.6 on 2026-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_data',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
